### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by liyanhrxy** [neo-project/neo-cli#174] opened 2018-06-08 06:15 UTC
Unhandled Exception: System.ArgumentException: An item with the same key has already been added. Key: System.Threading.Tasks.Task`1[System.Threading.Tasks.VoidTaskResult]
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Neo.Network.LocalNode.<>c__DisplayClass61_0.<ConnectToPeersLoop>g__connectToPeers|0(IEnumerable`1 ipEndPoints)
   at Neo.Network.LocalNode.ConnectToPeersLoop()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
Aborted

**Comment by erikzhang** [comment] 2018-06-09 10:28
Duplicate of #159

**Closed by erikzhang** 2018-06-09 10:28 UTC
Labels: duplicate
