### ISSUE TITLE
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by Cherisher** [neo-project/neo-cli#186] opened 2018-06-29 02:45 UTC
[04:44:50] OnChangeViewReceived: height=2443348 view=0 index=4 nv=1

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Neo.Consensus.ConsensusContext.ChangeView(Byte view_number)
   at Neo.Consensus.ConsensusService.InitializeConsensus(Byte view_number)
   at Neo.Consensus.ConsensusService.LocalNode_InventoryReceived(Object sender, IInventory inventory)
   at Neo.Network.LocalNode.Relay(IInventory inventory)
   at Neo.Network.LocalNode.RemoteNode_InventoryReceived(Object sender, IInventory inventory)
   at Neo.Network.RemoteNode.OnInventoryReceived(IInventory inventory)
   at Neo.Network.RemoteNode.<StartProtocol>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by erikzhang** [comment] 2018-06-29 06:43
Duplicate of #185

**Closed by erikzhang** 2018-06-29 06:43 UTC
Labels: duplicate
