### ISSUE TITLE
Neo CLI v2.7.1 can not run on Windows Server 2008 , please check the bug, thanks!

### ISSUE THREAD

**Issue by kevingwang** [neo-project/neo-cli#109] opened 2018-02-09 06:05 UTC
Neo CLI v2.7.1 can not run on Windows Server 2008 , please check the bug, thanks!

**Comment by Ray-77** [comment] 2018-02-09 06:31
Have you install it https://www.microsoft.com/zh-cn/download/details.aspx?id=26755 in your computer ?
![2](https://user-images.githubusercontent.com/17636881/36014647-d97a0a96-0da5-11e8-97aa-468e46dd6efb.png)

**Comment by erikzhang** [comment] 2018-02-09 06:33
Duplicate of #63

**Comment by kevingwang** [comment] 2018-02-09 06:54
I have installed https://www.microsoft.com/zh-cn/download/details.aspx?id=26755 , it does not work.

**Comment by kevingwang** [comment] 2018-02-09 06:57
I have downloaded this pack and installed it, actually my system does not need it, and the problem is still the same.

![neo](https://user-images.githubusercontent.com/36290679/36015460-7caa917e-0da9-11e8-8b6f-79a4e5c7ed13.PNG)
![neo2](https://user-images.githubusercontent.com/36290679/36015464-8193ddf8-0da9-11e8-9f7e-4b9e80dc2d6a.PNG)

**Comment by kevingwang** [comment] 2018-02-09 07:04
Why your application name is neo-cli.exe , but my application name is neo-cli.dll ? 
This two programs are not the same, that means neo-cli.dll has bugs on Windows Server 2008 , please check it ,thanks!

**Comment by Ray-77** [comment] 2018-02-09 07:05
Maybe you need to install thishttps://www.microsoft.com/zh-cn/download/details.aspx?id=1671

**Comment by kevingwang** [comment] 2018-02-09 07:10
Already try, can not install it.
![neo3](https://user-images.githubusercontent.com/36290679/36015889-6b623dde-0dab-11e8-81ac-35e94f9afdfd.PNG)

**Comment by kevingwang** [comment] 2018-02-09 07:17
Could you please try to install **neo-cli.dll**  but not  **neo-cli.exe**  on Windows Sever 2008 ? 
Thanks!

**Comment by erikzhang** [comment] 2018-02-09 07:19
I think this pack is for Windows Server 2008 R2, not for 2008.

**Comment by Ray-77** [comment] 2018-02-09 07:19
Try this https://www.microsoft.com/zh-cn/download/details.aspx?id=26772

**Comment by kevingwang** [comment] 2018-02-09 07:25
Aleary try to install https://www.microsoft.com/zh-cn/download/details.aspx?id=26772
,it does not work.

**Comment by erikzhang** [comment] 2018-02-09 07:30
Can you run other .net core applications?

**Comment by kevingwang** [comment] 2018-02-09 07:31
I think there are some differences between neo-cli.dll and neo-cli.exe .
Could you please try to install neo-cli.dll on Windows Sever 2008 because your publication version is neo-cli.dll but not neo-cli.exe ? 
Thanks!

**Comment by erikzhang** [comment] 2018-02-09 07:35
They are the same. `neo-cli.exe` is a wrap of `dotnet neo-cli.dll` command.

**Comment by kevingwang** [comment] 2018-02-09 07:40
Could you please send me a copy of neo-cli.exe  ? I want to try it on my system , thanks!

**Comment by erikzhang** [comment] 2018-02-09 07:52
https://github.com/neo-project/neo-cli/releases/tag/v2.7.1
You can download it from neo-cli-win7-x64.zip.

**Comment by kevingwang** [comment] 2018-02-09 09:48
Already try,the problem is the same.
![neo5](https://user-images.githubusercontent.com/36290679/36021652-641af56e-0dc1-11e8-83fe-49c96920cc9e.PNG)

**Comment by kevingwang** [comment] 2018-02-09 09:50
already install dotnet 4.6 success but still the problem

**Comment by kevingwang** [comment] 2018-02-09 09:54
That means neo-cli.dll on run on Windows Server 2008 R2 , but can not run on Windows Sever 2008 SP2 and Windows vista.

**Closed** 2018-05-29 07:30 UTC
Labels: duplicate
