### ISSUE TITLE
MacOS CLI Error:Attempt to free invalid pointer 0x7fb5bce0e640

### ISSUE THREAD

**Issue by liguobao** [neo-project/neo-cli#169] opened 2018-05-29 08:52 UTC
leveldb is installed.
error message:
Attempt to free invalid pointer 0x7fb5bce0e640

**Comment by erikzhang** [comment] 2018-05-29 09:55
Duplicate of #147

**Closed by erikzhang** 2018-05-29 09:55 UTC
Labels: duplicate

**Comment by hal0x2328** [comment] 2019-03-14 02:39
Alternate fix without having to switch to rocksdb, just use this command line to start neo-cli: 
```
DYLD_INSERT_LIBRARIES=/usr/local/lib/libtcmalloc.dylib dotnet ./neo-cli.dll
```
