### ISSUE TITLE
Exporting blockchain state

### ISSUE THREAD

**Issue by khelle** [neo-project/neo-cli#117] opened 2018-02-20 11:35 UTC
I see there is CLI command to export blockchain state via `export blocks`. However, I do not see similar option to be done via RPC. Is it possible to export the whole blockchain remotely?

**Comment by vncoelho** [comment] 2019-05-22 22:13
We are currently discussing it in another threads, @khelle.

The discussions is surrounding exporting tx's states for NEO 2.x.
However, using Merkle Patricia Trie or Sparse Trees may be the best way to proceed.

I think that I will leave this issue closed because it is kind of a duplicate of some of other discussions going on.
Fell free to reopen and thanks for this insight.

**Closed by vncoelho** 2019-05-22 22:13 UTC
Labels: enhancement
