### ISSUE TITLE
Server stops on putty disconnect for neo-cli

### ISSUE THREAD

**Issue by innvonix-git** [neo-project/neo-cli#148] opened 2018-05-04 04:43 UTC
Hello,
I am starting neo-cli server on my vps and completed sync. It is working fine. When i close my putty window, rpc server stops and sync also stops. Is there any way to make it continuee working in background ?
I have one another questions also can i deploy testnet and mainnet both on my server on different folders is it possible ?

**Comment by erikzhang** [comment] 2018-05-04 09:54
Duplicate of #48

**Comment by purplesoft-io** [comment] 2018-05-13 13:59
Hello to all,
I've edited neo-cli command line parser to allow wallet unlock and start rpc.
this is the pull request link: #151
and this is my forked branched repo: https://github.com/purplesoft-io/neo-cli/tree/neo-cli-daemon-with-wallet-unlock

usage:
dotnet neo-cli.dll --rpcwallet "/home/user/walletpath/wallet.db3" "W4LL3tP4sSw0rD 01"
dotnet neo-cli.dll --rpcwallet "/home/user/walletpath/wallet.json" "W4LL3tP4sSw0rD 01"

tiziano@purplesoft.io

Donations are welcome XD we are developing NEO WEB PANEL MANAGER for NEO NODES (also private deploy of NEO blockchain).
NEO: AYUd4G2dNXAEyUxkZGyMdXAnJ396jJfNDz
ETC: 0x982e45402ad06d0a01f3e54732b28c76d9870422
BTC: 1HxdgF6WsvcRVNiXhz6jZgbD9eopvzAxap
ETH: 0x5cb3784e71710f681410d30d615a3b3bb3c24ff1

**Closed** 2018-05-18 05:40 UTC
Labels: duplicate
