### ISSUE TITLE
how to run neo-cli as long live backend server?

### ISSUE THREAD

**Issue by LoranceChen** [neo-project/neo-cli#143] opened 2018-04-25 08:49 UTC
Running neo-cli as repl and listening http RPC is great. Could it be run as backend server even though I close ssh session?  
I want build a RPC server for ourself client program.

**Comment by erikzhang** [comment] 2018-04-25 09:43
Duplicate of #48

**Comment by erikzhang** [comment] 2018-04-25 09:44
screen -S neo ./neo-cli --rpc

**Closed by erikzhang** 2018-04-25 09:44 UTC
Labels: duplicate
