### ISSUE TITLE
NEO sent to NEO WALLET has not arrived.

### ISSUE THREAD

**Issue by episteme7905** [neo-project/neo-cli#92] opened 2018-01-10 04:31 UTC
Transaction appears at Neotracker but does not appear in NEO WALLET - shows zero balance.

My receive address: AbTFuqir5bcmWdmbBWEBNtqnkpTCy5WeZB

How long should this transaction take?

When I search the address at Neotracker under the heading First transaction it states UNSPENT.
What does UNSPENT mean?

If the address can be seen in all the Block Explorers why doesn't it appear or show in my NEO-WALLET!?

Please help. 

Many thanks and greetings from south korea

**Comment by erikzhang** [comment] 2018-01-10 10:17
Duplicate of neo-project/neo-gui#142

**Closed by erikzhang** 2018-01-10 10:17 UTC
Labels: duplicate, help wanted
