### ISSUE TITLE
Use readline package in neo-cli for history of commands

### ISSUE THREAD

**Issue by mlabbaf** [neo-project/neo-cli#260] opened 2018-11-02 19:13 UTC
Hi,

Thanks for developing the neo-cli. I use it beside neo-privnet and it's good.
However, one thing is bothering me. It was that neo-cli cannot maintain the command history.
I wrote a CLI (command line interface) for another project and in that we use the readline package for command history. I'm interested to know, is there any plan to add this capability to neo-cli package?
Also, I can integrate readline package to neo-cli by myself based on my previous experience although is not a hard task

**Comment by belane** [comment] 2018-11-03 02:44
@mlabbaf, would be great to have it, this function is builtin on windows but not yet in linux shell.

**Comment by belane** [comment] 2018-11-08 23:07
@mlabbaf I've added basic readline integration here https://github.com/belane/neo-cli/commit/04d87803a540a6a1b46c9ad7a4b78a9743acd625 and is working well, can you check it and tell me if we need any improvements more?

**Comment by mlabbaf** [comment] 2018-11-13 18:36
Thanks for your development and sorry for my delay. 

I check it and history is worked, however I think is somehow slow !!
Also, it's lack the tab completion feature.
I previously used ReadLine package in C based CLI and I attach a sample C program that used ReadLine package.
To compile it, use the following command:
gcc TabCompletion.c -lreadline -lncurses -lpthread
To compile this code, readline and ncurses should be installed. (sudo apt-get install libreadline-dev lib32ncurses5-dev)

Also, the following links can be helpful.
http://web.mit.edu/gnu/doc/html/rlman_2.html
https://eli.thegreenplace.net/2016/basics-of-using-the-readline-library/

attached c code:
[TabCompletion.c.tar.gz](https://github.com/neo-project/neo-cli/files/2577546/TabCompletion.c.tar.gz)

**Comment by mlabbaf** [comment] 2018-11-14 13:49
I test it with and without ReadLine. Unfortunately, when I use up arrow key twice, it's slow ! I didn't see this in C version !

However, if we assume the performance issue is fixed, is ReadLine package be the correct choice?
We use it in our C based CLI. In that project, the important factors were command history and tab completion.

**Comment by belane** [comment] 2018-11-14 14:10
It should have been solved because I'm trying (debian 9.5 and windows 10) and I don't see any performance problem, I will do more testing to try to reproduce.

I have chosen ReadLine nuget package as neo-cli is on C# as will be easy to maintain, do you think it would be a problem?

**Comment by mlabbaf** [comment] 2018-11-15 16:12
It's weird. The same as you told, when I use the tmux, the result is different than when I use terminal !!

**Comment by belane** [comment] 2018-11-19 13:46
I've tracked this behavior to these netcore issues, so we have to find a workarround until they fix it or find another solution.

https://github.com/dotnet/corefx/issues/31517
https://github.com/dotnet/cli/issues/10101

**Comment by mlabbaf** [comment] 2018-11-24 11:00
I have a basic question. Can I know the main reason that neo-cli is written in C#?
I have advanced experience in developing in C language that biased me to write CLI in C language. Also, based on my short search, python is a good language for developing CLI.

**Comment by belane** [comment] 2018-11-24 19:00
I guess there is no specific answer to this. I think C# is a fully valid language like any other, also you can find implementations in other languages like neo-python.

**Comment by lock9** [comment] 2019-07-15 23:50
Hello guys, 
This looks solved to me, I'm closing it, ok? If you guys think it is a mistake, please reopen this issue. Thanks.

**Closed by lock9** 2019-07-15 23:50 UTC
Labels: enhancement
