### ISSUE TITLE
Seed stuck at 2000190

### ISSUE THREAD

**Issue by panther142** [neo-project/neo-cli#121] opened 2018-03-09 00:58 UTC
My seed (54.66.154.140) is stuck at block height 2000190 and wont progress any further.

I have deleted the Chain folder, downloaded Chain.acc and started a re-sync. Did not fix it.  

I have also deleted peers.dat and a new one has been created automatically.

This has only started to occur since the network outage this morning and it appears (looking at monitor.cityofzion.io) there are many other seeds stuck on the same block.

@erikzhang

**Comment by bitcodernull** [comment] 2018-03-09 03:13
i have two nodes, one of node met the same problem

**Comment by erikzhang** [comment] 2018-03-09 04:55
Duplicate of #100

**Closed by erikzhang** 2018-03-09 04:55 UTC
