### ISSUE TITLE
NEO synchronization time and synchronization deadlocks

### ISSUE THREAD

**Issue by khelle** [neo-project/neo-cli#100] opened 2018-01-19 12:52 UTC
How long does it take for NEO to sync from zero to the newest block? I have been working with around 50 full-nodes up to this day and the longest it took for any of it to fully sync was about two days. I have been running NEO on the same class server and after 20hrs I am at block 210338, while https://neoexplorer.co/ shows me the highest one is at 1828385. Dividing this value gives me the number of ~9 days needed for sync. If I assume the NEO behaves the same other cryptos, and the most 10-20% recent ones will sync slower I can probably assume full sync will be completed in 14 days. This does not look normal. Why is it so slow? Is there any way to make it faster?

My specs:
- Dedicated server
- Ubuntu 16.04 x64
- 64 GB RAM
- SSD
- Network 100 Mbps
- NEO ver 2.6.0

**Comment by jonatanblockchain** [comment] 2018-01-22 09:30
You can speed up downloading a copy of the blockchain
https://github.com/CityOfZion/awesome-neo

http://docs.neo.org/en-us/node/gui.html#synchronizing-blockchain-data

**Comment by khelle** [comment] 2018-01-22 10:01
@jonatanblockchain Hey, thanks for you contribution to this topic. I used this file on development server, but for now I am synchronizing production one, and I do not consider it safe to download blockchain in that case. Did you try to sync the blockchain from zero yourself? Did it take you the same amount of time too?

After 3 days I am at block 1342698, which is slightly better than expected, but still overall very long...

**Comment by jonatanblockchain** [comment] 2018-01-22 10:04
Your are right. It takes time. 
Yes, I would like to test 2.6.0 because its come with some optimizations.

**Comment by khelle** [comment] 2018-01-26 15:52
@jonatanblockchain I am using 2.6.0. The full synchronization took 7 days, then worked fine for few hours and now is stuck at block 1858120 which is 200 blocks behind current top. Does NEO have problems with being stuck randomly? Is there any way to prevent this unreliability?

**Comment by jonatanblockchain** [comment] 2018-01-26 16:03
I will try 2.6.0 version at weekend. I let you know.

**Comment by khelle** [comment] 2018-01-27 12:18
It unstuck for a while, catched up to block 1860096 and now is re-stuck , being about 800 blocks behind the current top. I also see, the are stuck explorers like this https://neoexplorer.co/ one. It does not seem to be my single issue, but rather something common in this network.  I am not able to integrated this to the payment system when it has frequent problems like that. @erikzhang Any info on this?

**Comment by khelle** [comment] 2018-01-29 09:45
After two days I am still at block 1860096. Start consensus returns me only first "onStart" log, then nothing. RPC command to return list of peers shows me there are some, so the node connects somewhere. I have no idea how to push it further

**Comment by jonatanblockchain** [comment] 2018-01-29 09:51
Try:
1. Rename Chain folder to ChainTemp
2. Download 'blockchain bootstrap offline' from here: https://github.com/CityOfZion/awesome-neo#blockchain-bootstrap-files (file MainNet (MEGA - Chain.zip) - 1/23/2018)
3. Copy/Move the chain.zip folder on the neo-cli root folder
4. Start neo-cli

**Comment by khelle** [comment] 2018-01-29 09:53
@jonatanblockchain I won't be downloading chain from anywhere else than directly from blockchain. Besides, this does not answer my question - the node did in fact sync up at some point and I was able to send and receive transactions. THEN it got stuck. Few hours later.

**Comment by jonatanblockchain** [comment] 2018-01-29 10:03
I know. Another option is rename the chain folder and start again. There is no option to resume.

**Comment by khelle** [comment] 2018-01-29 11:26
@jonatanblockchain how there is no option to resume? Syncing of blockchain is a continous process, not finite action that needs to be done only once.

**Comment by jonatanblockchain** [comment] 2018-01-29 13:31
An option on neo-cli to resume/force is case you are stuck at some block.

**Comment by khelle** [comment] 2018-01-29 13:49
@jonatanblockchain I dont understand what you are telling me now. Do you tell me that there is an option for that and I should re-run my node with it, or do you tell me there is no option for that? I mean... the node should resolve synchronization by itself... does it require manual rollbacks?

**Comment by jyap808** [comment] 2018-02-05 06:48
Yes, NEO sync gets stuck randomly.

Running 2.7.1

**Comment by PeterLinX** [comment] 2018-02-05 10:57
@khelle @jyap808 
1. Rename your former "Chain" folder or just move it away.
2. Download the offline-data package(http://static.neo.org/client/chain.acc.zip) and copy it into the same folder as neo-cli.dll is.
3. Start your neo-cli.
4. If the sync process stuck at some height then close it and start again.
5. If your node cannot find any other nodes, you can start neo-cli with command --nopeers, it looks like "dotnet neo-cli.dll --nopeers".

**Comment by PeterLinX** [comment] 2018-02-05 11:02
@khelle if you think it's not safe, you need to download it all over and it really takes time. Because you have almost 2000000 blocks to sync with. Also, as you know, the speed of syncing data depends on p2p network, if your server have very few nodes connection then your sync process will slow down big time.

**Comment by khelle** [comment] 2018-02-07 18:41
@PeterLinX  I don't understand how it is possible for cryptocurrency node to be permanently stuck on some block? Can you explain me what is happening there? I mean, syncing is not a finite, but conitnous process and is the fundamental part of any cryptocurrency. How is it possible it stucks? Does the problem lie with untrustworthy peers that create local chain splits, and the node is not able to resolve it back to the "real" chain again? If yes, then why the is no "--rollback=amountOfBlocks" flag of any sort? Then again, If I need to download the chain to fix the problem instead of using my partially synced one, then how does it fix the problem? Why downloaded chain would work and mine not? Is there a way to make safe snapshots of my own chain that could be used that way? Would I be able to create given snapshot - lets say - every hour, so if node stucks I could use it to continue sync faster than from genesis block?

**Comment by coranos** [comment] 2018-02-16 13:34
@khelle when it gets stuck, have you checked how many nodes it is connected to?

Mine gets stuck periodically. What I do is delete peers.dat and restart.

It seems like sometimes all the nodes disconnect, and there's no logic to restart from the bootstrap nodes.

**Comment by khelle** [comment] 2018-02-20 11:29
@coranos Interesting. I dont remember checking on any "show node" command, but I surely used "getpeers" which returned me quite a big array of nodes and "getconnectioncount" was greater than zero. I am not sure if this RPC calls check the same thing as "show node" command tough.

**Comment by coranos** [comment] 2018-02-21 03:48
It does show the same information. Did you check how many peers were under "Good peers"?
If the connection count was nonzero, not sure what the problem is.

**Closed** 2018-03-21 08:55 UTC
Labels: help wanted

**Comment by deoxen0n2** [comment] 2018-03-21 11:30
Hi,

We have block stuck since NEO version 2.7.1 on 3 NEO nodes. Then we decided to start new NEO node with NEO version 2.7.3 but eventually it got stuck too. We tried both with and without bootstrap file. This is the final result (synced from the start -- not using bootstrap file):

```
neo> show state
Height: 0/2022689/2022689, Nodes: 7
neo> show node
::ffff:xxx.241.6.245 port:10333 listen:10333 height:2047944 [1/7]
::ffff:xxx.15.47.180 port:10333 listen:10333 height:2022689 [2/7]
::ffff:xxx.55.45.45 port:10333 listen:10333 height:2047951 [3/7]
::ffff:xxx.160.95.140 port:10333 listen:10333 height:2047970 [4/7]
::ffff:xxx.130.76.116 port:10333 listen:10333 height:2047989 [5/7]
::ffff:xxx.197.14.66 port:10333 listen:10333 height:2022689 [6/7]
::ffff:xxx.104.51.54 port:10333 listen:10333 height:2048029 [7/7]
```

It sees the higher height on different nodes but still it will not sync to that height and `error.log` also shows nothing. Please advice.

**Comment by okarpov** [comment] 2018-05-07 08:04
opening and closing NEO GUI always crashes, and windows error reporting add new line with error like this:

Source
neo-gui

Summary
Stopped working

Date
‎5/‎7/‎2018 10:56 AM

Status
Report sent

Description
Faulting Application Path:	D:\xxxx\Bitcoin\Antshares\NEO\neo-gui.exe

Problem signature
Problem Event Name:	CLR20r3
Problem Signature 01:	neo-gui.exe
Problem Signature 02:	2.6.6596.21976
Problem Signature 03:	5a6564b1
Problem Signature 04:	mscorlib
Problem Signature 05:	4.7.2633.0
Problem Signature 06:	5a4ed653
Problem Signature 07:	41bc
Problem Signature 08:	1a
Problem Signature 09:	System.ObjectDisposedException
OS Version:	10.0.16299.2.0.0.256.48
Locale ID:	1033
Additional Information 1:	27ab
Additional Information 2:	27ab2585c97dd6cf2f96ecda6c6153fa
Additional Information 3:	f6ec
Additional Information 4:	f6ec0d17b3f6d8d31d169f0606072308

Extra information about the problem
Bucket ID:	db97ab94fd6d08346378034b9a958164 (1402874907176829284)

**Comment by r3lik** [comment] 2018-09-11 23:46
please re-open this issue.

**Comment by l-vitall** [comment] 2019-01-25 16:37
Testnet get stuck again at block 2,241,608 more than two hours ago, https://neoscan-testnet.io also stays on this block number currently.
