### ISSUE TITLE
“Unable to load DLL 'libleveldb' on Windows Server 2012 R2

### ISSUE THREAD

**Issue by heavenwing** [neo-project/neo-cli#198] opened 2018-07-13 05:09 UTC
I installed .NET Core 2.1.2 Runtime and .NET 4.7.2.
When I tried to run neo-cli.exe , I got this error.
I try to installing VC++ 2010 Redis or 2012 Redis, it is not working yet.

**Comment by erikzhang** [comment] 2018-07-13 09:42
Duplicate of #130

**Comment by heavenwing** [comment] 2018-07-21 02:10
why neo-cli can run on my Windows 10 machine? It doesn't compile leveldb.
And I try again on Windows Server 2016 on AzureCN, it have same problem.
But my local server with Windows Server 2016 is fine.

**Closed** 2019-05-22 22:03 UTC
Labels: duplicate
