### ISSUE TITLE
Stuck at block 3773043

### ISSUE THREAD

**Issue by i3bitcoin** [neo-project/neo-cli#370] opened 2019-05-23 08:02 UTC
Hi,

My node is stuck at 3773043 block, Neo CLI v2.9.2.

After upgrading to Neo CLI v2.10.2 and syncing from scratch, I got the same issue.

I see that many nodes are experiencing this problem also, according to the peers list.

Is there any solution?

**Comment by erikzhang** [comment] 2019-05-23 08:06
Duplicate of #365

**Closed by erikzhang** 2019-05-23 08:06 UTC
Labels: duplicate
